### ISSUE TITLE
bot stopped posting daily puzzles

### ISSUE THREAD

**Issue by benvanwerkhoven** [arex1337/lichess-daily-puzzle-slack-app#7]
Hi There! First of all thank you for building this app! I've enjoyed the daily puzzles with my coffee in the morning at the start of the work day for a very long time!

On March 5 however the bot stopped posting puzzles in our #chess channel on our slack space. I've tried to set the puzzletime again in the hope to get the bot to start posting puzzles again, but that hasn't worked so far. I've also tried /puzzle for a few on-demand puzzles in the hopes getting it going again, but to no avail yet. Any ideas?

Could it have to do with the fact that the user who invited the bot in the first place has left the organization? Should I try to re-add the bot perhaps? I'm not an administrator of this particular workspace, so I would need to see if I can do that.

Best,
Ben

**Comment by canut** [comment]
Hi
Same issue here and the release of #8 didn’t fix it. Using the /puzzle command works. It manually triggers the posting to Slack.
Removing and reinstalling the Slack app didn’t fix it neither.

**Comment by canut** [comment]
Hi,
Issue seems to be fixed since Friday 26/03. Daily puzzle is now correctly posted every day.

**Comment by benvanwerkhoven** [comment]
Indeed! It's working again for our channel as well as of the 26st.
